accessing
recordedException: anObject

	recordedException := anObject