1 - exception test
b
	
	self error: 'b'